# /*********************************************************************************
# * 
# *  Created by Xiang on 2020/3/9.
# *  Copyright (c) 2020-2021 Xiang. All rights reserved.
# * 
# **********************************************************************************/
#
# When running the progrm with DEBUGLOG=1, use libpipeline_debug.a instead of libpipeline.a 

all:
	gcc -o sim main.c project1.c libpipeline.a
clean:
	rm -f pipeline
	rm -rf logs
